journal_service:
  - role: "[Reviewer]"
    name: "CCF Transactions on Pervasive Computing and Interaction"
    abbr: "TPCI"
    years: ["2025"]

  - role: "[Reviewer]"
    name: "IEEE Transactions on Services Computing"
    abbr: "TSC"
    years: ["2025"]

conference_services:
  - role: "[Artifact Evaluation Committee]"
    conference: "USENIX Security Symposium"
    abbr: "USENIX Security"
    years: ["2026"]

#editorial_boards:
#  - role: "Associate Editor"
#    journal: "IEEE Security & Privacy Magazine"
#    abbr: "S&P"
#    period: "2023-present"
